theme: jekyll-theme-minimal
title: Black-box Adversarial Attacks on Network-wide Multi-step Traffic State Prediction Models
description: Accepted to IEEE International Conference on Intelligent Transportation Systems (ITSC), 2021
